plugins {
    id 'com.android.application' version '8.7.3'
}

android {
    namespace 'com.mikedg.android.glass.launchy'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jtrou.glassapps'
        minSdk 27
        targetSdk 34
        versionCode 2
        versionName '2.0-ee2'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-project.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
